name: CMake
on: [push, pull_request]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cmake -S . -B build/
      - run: make -C build/
      - run: ./build/HOPE
